service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: newtest
    handler: lambda_function.lambda_handler
    description: newtest
    timeout: 
    memorySize: 
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
