service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  proxy:
    handler: index.handler
    events:
     - httpApi:
         path: /test
         method: ANY
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
