service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true
  run: |
    --function-name ${{ env.AWS_LAMBDA_FUNC_NAME }} \
  env:
  AWS_LAMBDA_FUNC_NAME: newtest
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
